name:                Parskell
version:             0.1.0.0
github:              "Hafflationist/Parskell"
license:             BSD3
author:              "Hafflationist"
maintainer:          "Author email here"
copyright:           "2020 Hafflationist"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Hafflationist/Parskell#readme>

dependencies:
- base >= 4.13 && < 5
- text
- hspec
- QuickCheck
- HUnit
- either
- split
library:
  source-dirs: src

executables:
  Parskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Parskell

tests:
  Parskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Parskell
